In [3]:
import numpy as np
 
data =np.random.randint(0,100,(3,3))

In [4]:
data

array([[62, 69, 77],
       [64, 16, 77],
       [21, 65, 81]], dtype=int32)

In [6]:
data.max(axis=0)

array([64, 69, 81], dtype=int32)

np.arrange(0,100,2) prints all the num accorng to rnge and condition
np.linspace(0,10,4)  dference btween the two num is equal
np.eye(3)  
data.shape,data.size,data.ndim

In [7]:
data.min(axis=0)

array([21, 16, 77], dtype=int32)

In [ ]:
data.sum()
data.sum(axis=0)## it sum all values in each column
data.sum(axis=1)## it sum all values in each row

array([208, 157, 167])

In [13]:
data.min()

np.int32(16)

In [ ]:
import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a,b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ -9 -18 -27 -36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [ ]:
import numpy as np

data = np. random.randint(1,100,10)

In [22]:
data

array([67, 86,  9, 96, 66, 53, 84, 97, 47, 35], dtype=int32)

In [ ]:
#mode
np.argmax(data)

np.int64(7)

In [28]:
#mod
np.min(data)
np.max(data)

np.int32(97)

In [37]:
import  numpy as np

data=np.array([10,20,np.nan,40,np.nan,90])
print("orginal data :", data)

print("null positions are : ",np.isnan(data))

print("total null points are : ",np.isnan(data).sum())

clean_data=data[~np.isnan(data)]
print("aftr removing null values:", clean_data)

replace_null= np.nan_to_num(data,0)
print("replacing null to 0 :",replace_null)

mean_value=np.nanmean(data)
replace_mean=np.where(np.isnan(data),mean_value,data)

orginal data : [10. 20. nan 40. nan 90.]
null positions are :  [False False  True False  True False]
total null points are :  2
aftr removing null values: [10. 20. 40. 90.]
replacing null to 0 : [10. 20.  0. 40.  0. 90.]
