In [3]:
import numpy as np


b_data=np.array([
[101, 50000, 720, 30, 5],
[102,120000,680,60,7],
[103, 90000,600,12,2],
[104,150000,810,80,10],
[105,20000,650,40,3],
[106,300000,750,90,12],
[107,110000,820,55,6],
[108,70000,710,20,4],
[109,40000,690,15,2],
[110,250000,830,65,9]
])

print(b_data)

[[   101  50000    720     30      5]
 [   102 120000    680     60      7]
 [   103  90000    600     12      2]
 [   104 150000    810     80     10]
 [   105  20000    650     40      3]
 [   106 300000    750     90     12]
 [   107 110000    820     55      6]
 [   108  70000    710     20      4]
 [   109  40000    690     15      2]
 [   110 250000    830     65      9]]


In [4]:
balances=b_data[:,1]

total_balance=np.sum(balances)

print(total_balance)

1200000


In [7]:
# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)
sorted=b_data[balances.argsort()]

print(sorted)


[[   105  20000    650     40      3]
 [   109  40000    690     15      2]
 [   101  50000    720     30      5]
 [   108  70000    710     20      4]
 [   103  90000    600     12      2]
 [   107 110000    820     55      6]
 [   102 120000    680     60      7]
 [   104 150000    810     80     10]
 [   110 250000    830     65      9]
 [   106 300000    750     90     12]]


In [9]:

# Q8.2: Sort the banking_data by credit score (descending)
sorted_des=b_data[balances.argsort()[::-1]]

print(sorted_des)

[[   106 300000    750     90     12]
 [   110 250000    830     65      9]
 [   104 150000    810     80     10]
 [   102 120000    680     60      7]
 [   107 110000    820     55      6]
 [   103  90000    600     12      2]
 [   108  70000    710     20      4]
 [   101  50000    720     30      5]
 [   109  40000    690     15      2]
 [   105  20000    650     40      3]]


In [11]:

# Q8.3: Find the indices that would sort the array by years active
indices=b_data[b_data[:,4].argsort()]

print(indices)


[[   103  90000    600     12      2]
 [   109  40000    690     15      2]
 [   105  20000    650     40      3]
 [   108  70000    710     20      4]
 [   101  50000    720     30      5]
 [   107 110000    820     55      6]
 [   102 120000    680     60      7]
 [   110 250000    830     65      9]
 [   104 150000    810     80     10]
 [   106 300000    750     90     12]]


In [17]:

# Q8.4: Find the customer with the second highest account balance
b=b_data[:,1].argsort()[::-1]
second_highest=b_data[b[1]]
print(second_highest)



[   110 250000    830     65      9]


In [21]:
# Q8.5: Find the customer with the lowest transaction count
c=b_data[b_data[:,3].argmin()]

print(c)

[  103 90000   600    12     2]


In [5]:
# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements

a=np.abs(b_data)

print(a)


[[   101  50000    720     30      5]
 [   102 120000    680     60      7]
 [   103  90000    600     12      2]
 [   104 150000    810     80     10]
 [   105  20000    650     40      3]
 [   106 300000    750     90     12]
 [   107 110000    820     55      6]
 [   108  70000    710     20      4]
 [   109  40000    690     15      2]
 [   110 250000    830     65      9]]


In [7]:

# Q9.2: Calculate the square root of all account balances

s=np.sqrt(balances)
print(s)

[223.60679775 346.41016151 300.         387.29833462 141.42135624
 547.72255751 331.66247904 264.57513111 200.         500.        ]


In [9]:


# Q9.3: Calculate the square of all credit scores

sq=np.square(b_data[:,2])
print(sq)

[518400 462400 360000 656100 422500 562500 672400 504100 476100 688900]


In [11]:


# Q9.4: Calculate the exponential of all transaction counts

exp_transactions = np.exp(b_data[:,3])
print(exp_transactions)

[1.06864746e+13 1.14200739e+26 1.62754791e+05 5.54062238e+34
 2.35385267e+17 1.22040329e+39 7.69478527e+23 4.85165195e+08
 3.26901737e+06 1.69488924e+28]


In [12]:
# Q9.5: Calculate the natural logarithm of all account balances

log_balance = np.log(b_data[:,1])
print(log_balance)

[10.81977828 11.69524702 11.40756495 11.91839057  9.90348755 12.61153775
 11.60823564 11.15625052 10.59663473 12.4292162 ]


In [14]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances

a=np.cumsum(balances)
print(a)

[  50000  170000  260000  410000  430000  730000  840000  910000  950000
 1200000]


In [15]:

# Q10.2: Calculate the cumulative product of transaction counts

b=np.cumprod(b_data[:,3])
print(b)

[              30             1800            21600          1728000
         69120000       6220800000     342144000000    6842880000000
  102643200000000 6671808000000000]


In [18]:
# Q10.3: Calculate the difference between consecutive account balances

c=np.diff(balances)
print(c)

[  70000  -30000   60000 -130000  280000 -190000  -40000  -30000  210000]


In [19]:

# Q10.4: Calculate the gradient of account balances

d=np.gradient(balances)
print(d)

[  70000.   20000.   15000.  -35000.   75000.   45000. -115000.  -35000.
   90000.  210000.]


In [ ]:
# Q10.5: Calculate the histogram of account balances with 5 bins


