In [2]:
import numpy as np


b_data=np.array([
[101, 50000, 720, 30, 5],
[102,120000,680,60,7],
[103, 90000,600,12,2],
[104,150000,810,80,10],
[105,20000,650,40,3],
[106,300000,750,90,12],
[107,110000,820,55,6],
[108,70000,710,20,4],
[109,40000,690,15,2],
[110,250000,830,65,9]
])

In [3]:
b_data

array([[   101,  50000,    720,     30,      5],
       [   102, 120000,    680,     60,      7],
       [   103,  90000,    600,     12,      2],
       [   104, 150000,    810,     80,     10],
       [   105,  20000,    650,     40,      3],
       [   106, 300000,    750,     90,     12],
       [   107, 110000,    820,     55,      6],
       [   108,  70000,    710,     20,      4],
       [   109,  40000,    690,     15,      2],
       [   110, 250000,    830,     65,      9]])

In [5]:
# Q1.1: Create a 4x4 identity matrix using np.eye()

np.eye(4)





array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# Q1.2: Create an array of 8 zeros using np.zeros()
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Q1.2: Create an array of 6 ones using np.ones()
np.ones(1)

array([1.])

In [12]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
# Q1.5: Create an array with 8? evenly spaced values from 0 to 100 using np.linspace()
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [17]:
# Question 2: Array Attributes and Information
# Q2.1: What is the shape of the banking_data array?

b_data.shape



(10, 5)

In [19]:
# Q2.2: What is the data type of the banking_data array?
b_data.dtype

dtype('int64')

In [20]:

# Q2.3: What is the size (total number of elements) of the banking_data array?

b_data.size

50

In [21]:
# Q2.4: What is the number of dimensions of the banking_data array?

b_data.ndim

2

In [22]:
# Q2.5: What is the memory size of the banking_data array in bytes?

b_data.nbytes

400

In [4]:
# Question 3: Indexing and Slicing
# Q3.1: Extract the first row of banking_data
b_data[1]


array([   102, 120000,    680,     60,      7])

In [5]:
# Q3.2: Extract the last row of banking_data

b_data[-1]

array([   110, 250000,    830,     65,      9])

In [6]:
# Q3.3: Extract the Account_Balance column (column index 1)

b_data[:,1]

array([ 50000, 120000,  90000, 150000,  20000, 300000, 110000,  70000,
        40000, 250000])

In [7]:
# Q3.4: Extract the first 4 rows and first 3 columns

b_data[:4,:3]

array([[   101,  50000,    720],
       [   102, 120000,    680],
       [   103,  90000,    600],
       [   104, 150000,    810]])

In [8]:
# Q3.5: Extract rows 3 to 7 (inclusive)

b_data[3:7]

array([[   104, 150000,    810,     80,     10],
       [   105,  20000,    650,     40,      3],
       [   106, 300000,    750,     90,     12],
       [   107, 110000,    820,     55,      6]])

In [4]:
# Question 4: Mathematical Operations
# Q4.1: Calculate the sum of all account balances
balances=b_data[:,1]

total_balance=np.sum(balances)

print(total_balance)

1200000


In [6]:
# Q4.2: Calculate the mean account balance

np.mean(balances)

np.float64(120000.0)

In [7]:
# Q4.3: Calculate the standard deviation of account balances
np.std(balances)

np.float64(86602.54037844387)

In [8]:

# Q4.4: Calculate the variance of account balances

np.var(balances)


np.float64(7500000000.0)

In [9]:
# Q4.5: Calculate the median account balance
np.median(balances)


np.float64(100000.0)

In [13]:
# Q5.1: Find the minimum and maximum account balances
np.min(balances)

np.max(balances)


np.int64(300000)

In [18]:
# Q5.2: Find the minimum and maximum credit scores
b_data
credit_score=b_data[:,2]

np.min(credit_score)

np.max(credit_score)

np.int64(830)

In [19]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

percentile=np.percentile(balances,[25,50,75])

print(percentile)

[ 55000. 100000. 142500.]


In [20]:
# Q5.4: Calculate the correlation between account balance and credit score

np.corrcoef(balances,credit_score)

array([[1.        , 0.55543962],
       [0.55543962, 1.        ]])

In [22]:
# Q5.5: Calculate the covariance between account balance and credit score

c=np.cov(balances,credit_score)
print(c[0,1])


3877777.7777777775


In [23]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns

b_data.reshape(5,10)




array([[   101,  50000,    720,     30,      5,    102, 120000,    680,
            60,      7],
       [   103,  90000,    600,     12,      2,    104, 150000,    810,
            80,     10],
       [   105,  20000,    650,     40,      3,    106, 300000,    750,
            90,     12],
       [   107, 110000,    820,     55,      6,    108,  70000,    710,
            20,      4],
       [   109,  40000,    690,     15,      2,    110, 250000,    830,
            65,      9]])

In [24]:

# Q6.2: Flatten the banking_data to a 1D array

b_data.flatten()

array([   101,  50000,    720,     30,      5,    102, 120000,    680,
           60,      7,    103,  90000,    600,     12,      2,    104,
       150000,    810,     80,     10,    105,  20000,    650,     40,
            3,    106, 300000,    750,     90,     12,    107, 110000,
          820,     55,      6,    108,  70000,    710,     20,      4,
          109,  40000,    690,     15,      2,    110, 250000,    830,
           65,      9])

In [26]:
# Q6.3: Transpose the banking_data
b_data.T

array([[   101,    102,    103,    104,    105,    106,    107,    108,
           109,    110],
       [ 50000, 120000,  90000, 150000,  20000, 300000, 110000,  70000,
         40000, 250000],
       [   720,    680,    600,    810,    650,    750,    820,    710,
           690,    830],
       [    30,     60,     12,     80,     40,     90,     55,     20,
            15,     65],
       [     5,      7,      2,     10,      3,     12,      6,      4,
             2,      9]])

In [28]:

# Q6.4: Split the banking_data into 2 equal parts vertically

np.vsplit(b_data,2)

[array([[   101,  50000,    720,     30,      5],
        [   102, 120000,    680,     60,      7],
        [   103,  90000,    600,     12,      2],
        [   104, 150000,    810,     80,     10],
        [   105,  20000,    650,     40,      3]]),
 array([[   106, 300000,    750,     90,     12],
        [   107, 110000,    820,     55,      6],
        [   108,  70000,    710,     20,      4],
        [   109,  40000,    690,     15,      2],
        [   110, 250000,    830,     65,      9]])]

In [30]:
# Q6.5: Split the banking_data into 2 equal parts horizontally


np.hsplit(b_data,2)

ValueError: array split does not result in an equal division

In [37]:
# Q7.1: Find customers with account balance greater than $100,000

balan=b_data[:,1]

result=b_data[balan>100000]

print(result)

[[   102 120000    680     60      7]
 [   104 150000    810     80     10]
 [   106 300000    750     90     12]
 [   107 110000    820     55      6]
 [   110 250000    830     65      9]]


In [39]:
# Q7.2: Find customers with credit score greater than 800

c=b_data[:,2]
c_r=b_data[c>800]

print(c_r)




[[   104 150000    810     80     10]
 [   107 110000    820     55      6]
 [   110 250000    830     65      9]]


In [40]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

result3=b_data[(b_data[:,3]>50)&(b_data[:,2]<750)]

print(result3)

[[   102 120000    680     60      7]]


In [42]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000

count= np.sum((b_data[:,1]>=10000)&(b_data[:,1]<=100000))

print(count)

5


In [43]:
# Q7.5: Find the index of the customer with the highest credit score

np.argmax(b_data[:,2])

np.int64(9)